
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_include_bluez_dbus_cpp_proxy_NetworkServer1_proxy_h_proxy_H_
#define _sdbuscpp_include_bluez_dbus_cpp_proxy_NetworkServer1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>


namespace org::bluez {
    class NetworkServer1_proxy {
    public:
        static constexpr auto INTERFACE_NAME = "org.bluez.NetworkServer1";

    protected:
        explicit NetworkServer1_proxy(sdbus::IProxy &proxy)
            : proxy_(proxy) {
        }

        ~NetworkServer1_proxy() = default;

    public:
        void Register(const std::string &uuid, const std::string &bridge) const {
            proxy_.callMethod("Register").onInterface(INTERFACE_NAME).withArguments(uuid, bridge);
        }

        void Unregister(const std::string &uuid) const {
            proxy_.callMethod("Unregister").onInterface(INTERFACE_NAME).withArguments(uuid);
        }

    private:
        sdbus::IProxy &proxy_;
    };
} // namespaces

#endif
